version: '3.8'

services:
  router-api:
    build: .
    image: hackathon-router:latest
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
    memswap_limit: 4G
    volumes:
      - ./input:/input
      - ./output:/output